"""LLM types — structured parser and drafter I/O. Never raw model text."""

from __future__ import annotations

from datetime import date
from decimal import Decimal

from pydantic import BaseModel, Field

from backend.engine.policy import ReplyIntent

CONFIDENCE_THRESHOLD = 0.7


class ParsedIntent(BaseModel):
    """Function-call payload from ``extract_reply_intent``."""

    intent: ReplyIntent
    promised_date: date | None = None
    promised_amount: Decimal | None = None
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str


class DraftRequest(BaseModel):
    """Facts injected into the template envelope — never generated by the LLM."""

    buyer_first_name: str
    invoice_number: str
    amount_inr: str
    due_date: str
    days_overdue: int
    payment_link: str
    tone: str = "firm_polite"


class DraftedMessage(BaseModel):
    """Personalized phrasing around locked facts."""

    body: str
    model: str
    input_tokens: int
    output_tokens: int
